export const metadata = {
    title: "Auth",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      
        <div className="">{children}</div>
    );
  }